spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:yourpassword@localhost:27018/productdb?authSource=admin
      auto-index-creation: true

server:
  port: 0
  address: 0.0.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${random.uuid}