spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:yourpassword@localhost:27018/productdb?authSource=admin
      auto-index-creation: true

server:
  port: 8081